build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm install
      - run:
          name: Front-End Build
          command: |
            npm run build
      - run:
          name: Front-End Deploy
          command: |
            npm run deploy
  