version: 2.1

orbs: 
  node: circleci/node@5.0.2
jobs:
  build:
    machine:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: npm install
      - run: npm run build
  test:
    machine:
      - image: cimg/base:2022.05
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm run test
  deploy:
    machine:
        image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm run deploy
workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test