version: 2.1

orbs: 
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade

      - checkout
      - run: npm install
      - run: npm run build
  deploy:
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm install
      - run: npm run deploy
workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build