version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm install
      - run:
          name: Front-End Build
          command: |
            npm run build
      - run:
          name: Front-End Deploy
          command: |
            aws s3 cp --recursive --scl public-read ./dist s3://store-frontent/
workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws
      - build
  