version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm install
      - run:
          name: Front-End Build
          command: |
            npm run build
      - run:
          name: Front-End Deploy
          command: |
            aws s3 cp --recursive --scl public-read ./dist s3://store-frontent/
  