version: 2.1

orbs: 
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm run test
  deploy:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm run deploy
workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test