version: 3.4.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Angular App Install Dependencies
          command: |
            npm install
      - run:
          name: Angular App Build
          command: |
            ng build
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: ng test
  deploy:
    machine:
        image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: ng deploy
    

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test