version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_Access_Key_ID
          aws-secret-access-key: AWS_Secret_Access_Key
          aws-region: DEFAULT_REGION
workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws